### PR TITLE
abstracted out working repository name and git email address

### PR DESCRIPTION
**Pull request by MareoRaft**
I'm trying to make Richard Bot a more general-purpose tool.

Well arguably RichardBot should remain as-is, and the more general purpose bot should be named "Git Bot".

-Matt

### CODE REVIEW

**Review by ghseeli — APPROVED** [review]

**Comment by ghseeli** [comment]
Wait, now I’m confused. Why is Richard bot turning into Axel bot? I liked the abstraction, but I don’t want to simply change the name.

**Review by ghseeli — CHANGES_REQUESTED** [review]
Everywhere richard was changed to axel, change it to a variable like $BOTNAME and then have the install fill it in.

**Comment by MareoRaft** [comment]
Oh no.  I made those changes AFTER making this pull request and I didn't realize the PR would include those changes.

**Comment by MareoRaft** [comment]
AxelBot is a specific implementation that I need for my course with Axel, not a general-purpose Git Bot.

**Comment by MareoRaft** [comment]
I think I'm going to make a brand new fork called "git-bot" for the abstraction.  I think Richard Bot should 'remain intact' because he is now himself a specific implementation.

**Comment by MareoRaft** [comment]
P.S. If you would like to be the owner of git-bot, since he was your idea in the first place, then go ahead and make the fork yourself and give me collaborator permissions.  I will get back to this later but for today I need to work on my AxelBot.  :)

**Pull request closed without merging**
